# post  http://localhost:8000/api/posts
# Content-Type: application/json
# Authorization: bearer {}

# {
#     "title": "My first post",
#     "body": "This is my first post"
# }
# post  http://localhost:8000/api/login
# Content-Type: application/json


# {
#     "email": "sh@gmail.com",
#     "password": "1234567"
# }

post http://localhost:8000/api/register
Content-Type: application/json


{
    "name": "mo",
    "email": "mo@gmail.com"
}






   


